SLACK_API_TOKEN: "***REMOVED***"

IBM_API_TOKEN: "***REMOVED***"

TWILIO_FROM_PHONE: "+***REMOVED***"
TWILIO_TO_PHONE: ""
TWILIO_ACCOUNT_SID: "***REMOVED***"
TWILIO_AUTH_TOKEN: "***REMOVED***"

POSTGRESQL_DATABASE_HOST: "***REMOVED***"
POSTGRESQL_DATABASE_DBNAME: "LEVY_POSTGRES"
POSTGRESQL_DATABASE_USER: "***REMOVED***"
POSTGRESQL_DATABASE_PASSWORD: "***REMOVED***"